version: '3.3'
services:
  application:
    image: uncanny
    container_name: uncanny
    env_file: .env.dev
    environment:
      - DATABASE_URL=postgres://postgres:development@postgresql/uncanny_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:10
    container_name: uncanny-postgres
    environment:
      - POSTGRES_DB=uncanny_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - uncanny_psql:/var/lib/postgresql/data
volumes:
  uncanny_psql:
